psabpf: Add shared library generation
P4-Research/psabpf pull request #34
Opened 2022-05-09 20:17 UTC by mestery

Enable shared library support by:

* Modifying build_libbpf.sh to pass CFLAGS, including -fPIC.
* Modify CMakeLists.txt to generate a shared library for psabpf.

Signed-off-by: Kyle Mestery <mestery@mestery.com>

2022-05-09 20:18 UTC, mestery commented
@tatry I think this should address all of your concerns. Also note that after a `make install`, I have to pass LD_LIBRARY_PATH to ensure it can find the library in /usr/local/lib:

```
vagrant@bullseye:/git/psabpf/build$ LD_LIBRARY_PATH=/usr/local/lib psabpf-ctl
Usage: psabpf-ctl [OPTIONS] OBJECT {COMMAND | help }
       psabpf-ctl help

       OBJECT := { clone-session |
                   multicast-group |
                   pipeline |
                   add-port |
                   del-port |
                   table |
                   action-selector |
                   meter |
                   digest |
                   counter }
       OPTIONS := {}
vagrant@bullseye:/git/psabpf/build$
```

2022-05-10 07:08 UTC, tatry requested changes
There is still missing switch for static/shared build. You can look at [P4C CMakeLists.txt](https://github.com/p4lang/p4c/blob/main/CMakeLists.txt) for reference how to do it.

2022-05-10 07:25 UTC, tatry commented
> ```
> vagrant@bullseye:/git/psabpf/build$ LD_LIBRARY_PATH=/usr/local/lib psabpf-ctl
> ```

I think that this is not the best way to do this, it requires a lot of additional characters to type on every `psabpf-ctl` invocation. There are two other methods that would be better:
- Change install prefix.
- Add library path system wide.

Every methods needs some documentation on it, at least in README.md, because they are not trivial.

2022-05-10 14:21 UTC, mestery commented
@tatry I believe I have now addressed all your concerns, let me know if you have additional suggestions. Thanks!

2022-05-11 06:22 UTC, tatry commented on README.md
> +   To build a shared library which the psabpf-ctl binary will link against:
The difference is only in cmake option? So there should be one instruction how to compile and separate paragraph on cmake options.

2022-05-11 06:23 UTC, tatry commented
Also please revert update of libbpf submodule.

2022-05-12 06:19 UTC, tatry approved these changes
LGTM, thank you.

2022-05-12 06:21 UTC, merged