Add feature of adding tuples to tuples_map
P4-Research/psabpf pull request #9
Opened 2022-02-25 16:29 UTC by kmateuszssak

This is needed for const entries for ternary tables

2022-03-01 09:00 UTC, tatry requested changes
For now 3 things, 2 of them below. It would be nice to see PTF tests with these changes before merge.

2022-03-02 11:50 UTC, kmateuszssak commented on lib/psabpf_pipeline.c
> +        if (load_btf(ctx, &btf_metadata) != NO_ERROR) {
Removed

2022-03-02 11:53 UTC, kmateuszssak commented on lib/psabpf_pipeline.c
> +        memcpy((void *)tuples_map_name + tuples_map_name_length, "_tuples_map", 12);
What we receive as an argument `map_name` it is tuple name. I changed the naming + I also tried to use "string" functions to perform string operations as you suggested.

2022-03-02 11:56 UTC, tatry commented on lib/psabpf_pipeline.c
> +        memcpy((void *)tuples_map_name + tuples_map_name_length, "_tuples_map", 12);
Its fine for me now.

2022-03-04 09:54 UTC, tatry approved these changes
LGTM

2022-03-09 08:11 UTC, merged